
# v: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.configure(2) do |config|
config.vm.provider :libvirt do |libvirt|
libvirt.host = '192.168.122.1'
libvirt.username = "4kvm"
libvirt.connect_via_ssh = true
libvirt.driver = "kvm"
libvirt.storage_pool_name = "VMS"
libvirt.storage :file, :size => '40G', :type => 'raw'
end

config.vm.box = "https://s3.otlabs.fr/index.php/s/tPeoTjFJ7I870GQ/download"
config.vm.provision "shell",
 run: "always",
 inline: " echo nameserver 8.8.8.8 > /etc/resolv.conf"
	config.vm.define :kenny1 do |kenny1|
	  kenny1.vm.hostname = "kenny1"

	  kenny1.vm.network :public_network, ip: '192.168.7.257', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
	  kenny1.vm.network :public_network, ip: '10.10.11.1', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
	 kenny1.vm.synced_folder "scripts", "/vagrant", disabled: false
	 kenny1.vm.provision "shell" , inline: "/vagrant/install.sh"
	 #kenny1.vm.provision "shell" , inline: "/vagrant/update.sh"
	 #kenny1.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh"
	  kenny1.vm.provision "shell" , inline: "/vagrant/deploy-gluster.sh"
	  kenny1.vm.provision "shell" , inline: "/vagrant/deploy-gogs.sh"
	  kenny1.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"
	  kenny1.vm.provider :libvirt do |domain|
	    domain.storage :file, :size => '20G'
	    domain.memory = 1024
	    domain.cpus = 1
	  end
	end
	 config.vm.define :kenny2 do |kenny2|
          kenny2.vm.hostname = "kenny2"
          kenny2.vm.network :public_network, ip: '192.168.7.258', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
          kenny2.vm.network :public_network, ip: '192.168.2.296', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
	  kenny2.vm.network :public_network, ip: '10.10.11.2', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
          kenny2.vm.synced_folder "scripts", "/vagrant", disabled: false
          kenny2.vm.provision "shell" , inline: "/vagrant/update.sh"
          kenny2.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh"
          kenny2.vm.provision "shell" , inline: "/vagrant/install.sh"
          kenny2.vm.provision "shell" , inline: "/vagrant/deploy-gluster.sh"
          kenny2.vm.provision "shell" , inline: "/vagrant/deploy-gogs.sh"
          kenny2.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"
          kenny2.vm.provider :libvirt do |domain|
	    domain.storage :file, :size => '20G'
            domain.memory = 1024
            domain.cpus = 1
          end
        end
         config.vm.define :kenny3 do |kenny3|
          kenny3.vm.hostname = "kenny3"
          kenny3.vm.network :public_network, ip: '192.168.7.259', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
	  kenny3.vm.network :public_network, ip: '192.168.2.297', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
	  kenny3.vm.network :public_network, ip: '10.10.11.3', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
          kenny3.vm.synced_folder "scripts", "/vagrant", disabled: false
          kenny3.vm.provision "shell" , inline: "/vagrant/update.sh"
          kenny3.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh"
          kenny3.vm.provision "shell" , inline: "/vagrant/install.sh"
          kenny3.vm.provision "shell" , inline: "/vagrant/deploy-gluster.sh"
          kenny3.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"
          kenny3.vm.provider :libvirt do |domain|
	    domain.storage :file, :size => '20G'
            domain.memory = 1024
            domain.cpus = 1
          end
        end
end
