# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure(2) do |config|
config.vm.provider :libvirt do |libvirt|
libvirt.host = '192.168.122.1'
libvirt.username = "4kvm"
libvirt.connect_via_ssh = true
libvirt.driver = "kvm"
libvirt.storage_pool_name = "VMS"
libvirt.storage :file, :size => '40G', :type => 'raw'
end


config.vm.box = "https://s3.otlabs.fr/index.php/s/tPeoTjFJ7I870GQ/download"
config.vm.provision "shell",
 run: "always",
 inline: " echo nameserver 8.8.8.8 > /etc/resolv.conf"
	config.vm.define :danemmy1 do |danemmy1|
 danemmy1.vm.hostname = "danemmy1"
	  danemmy1.vm.network :public_network, ip: '192.168.7.164, netmask: "22", :dev => "enp4s0", :mode => 'bridge'
	  danemmy1.vm.network :public_network, ip: '10.10.12.5', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
	  danemmy1.vm.synced_folder "./script", "/vagrant", disabled: false
	 # danemmy1.vm.provision "shell" , inline: "/vagrant/update.sh"
	  #danemmy1.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh"
	  danemmy1.vm.provision "shell" , inline: "/vagrant/install-docker.sh"
	  danemmy1.vm.provision "shell" , inline: "/vagrant/deploy-gluster.sh"
	 # danemmy1.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"
	  danemmy1.vm.provider :libvirt do |domain|
	    domain.memory = 1024
	    domain.cpus = 1
	  end
	end
	 config.vm.define :danemmy2 do |danemmy2| 
          danemmy2.vm.hostname = "danemmy2"
	  danemmy2.vm.network :public_network, ip: '192.168.2.162', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
	  danemmy2.vm.network :public_network, ip: '10.10.12.6', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
	  danemmy2.vm.network :public_network, ip: '192.168.7.162', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
          danemmy2.vm.synced_folder "./script", "/vagrant", disabled: false
          danemmy2.vm.provision "shell" , inline: "/vagrant/update.sh"
	 #danemmy2.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh"
          danemmy2.vm.provision "shell" , inline: "/vagrant/install-docker.sh"
		  danemmy2.vm.provision "shell" , inline: "/vagrant/deploy-gluster.sh"
         #danemmy2.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"
          danemmy2.vm.provider :libvirt do |domain|
            domain.memory = 1024
            domain.cpus = 1
          end
        end
         config.vm.define :danemmy3 do |danemmy3|
          danemmy3.vm.hostname = "danemmy3"
	  danemmy3.vm.network :public_network, ip: '192.168.2.169', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
	  danemmy3.vm.network :public_network, ip: '10.10.12.7', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
	  danemmy3.vm.network :public_network, ip: '192.168.7.163', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
          danemmy3.vm.synced_folder "./script", "/vagrant", disabled: false
         #danemmy3.vm.provision "shell" , inline: "/vagrant/update.sh"
	 #danemmy3.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh"
         danemmy3.vm.provision "shell" , inline: "/vagrant/install-docker.sh"
		 danemmy3.vm.provision "shell" , inline: "/vagrant/deploy-gluster.sh"
         #danemmy3.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"
          danemmy3.vm.provider :libvirt do |domain|
            domain.memory = 1024
            domain.cpus = 1
          end
        end
end
