# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure(2) do |config|
config.vm.provider :libvirt do |libvirt|
libvirt.host = '192.168.122.1'
libvirt.username = "4kvm"
libvirt.connect_via_ssh = true
libvirt.driver = "kvm"
libvirt.storage_pool_name = "VMS"
libvirt.storage :file, :size => '40G', :type => 'raw'

end

config.vm.box = "https://s3.otlabs.fr/index.php/s/tPeoTjFJ7I870GQ/download"
config.vm.provision "shell",
 run: "always",
 inline: " echo nameserver 8.8.8.8 > /etc/resolv.conf"
	config.vm.define :ayo1 do |ayo1|
	  ayo1.vm.hostname = "ayo1"
	  ayo1.vm.network :public_network, ip: '192.168.7.203', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
 ayo1.vm.network :public_network, ip: '10.10.10.1', netmask: "22", :dev => "enp4s0", :mode => 'bridge'	 
 ayo1.vm.synced_folder "./scripts", "/vagrant", disabled: false
	ayo1.vm.provision "shell" , inline: "/vagrant/update.sh"
	ayo1.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh" 
	ayo1.vm.provision "shell" , inline: "/vagrant/install_docker.sh"
	ayo1.vm.provision "shell" , inline: "/vagrant/install-gogs-compose.sh"
 	ayo1.vm.provision "shell" , inline: "/vagrant/install-gluster-compose.sh"
	ayo1.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"

	  ayo1.vm.provider :libvirt do |domain|
	    domain.memory = 1024
	    domain.cpus = 1
	  end
	end
config.vm.define :ayo2 do |ayo2|
          ayo2.vm.hostname = "ayo2"
          ayo2.vm.network :public_network, ip: '192.168.7.204', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
 ayo2.vm.network :public_network, ip: '192.168.2.254', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'   
ayo2.vm.network :public_network, ip: '10.10.10.2', netmask: "22", :dev => "enp4s0", :mode => 'bridge'         
 ayo2.vm.synced_folder "./scripts", "/vagrant", disabled: false
         ayo2.vm.provision "shell" , inline: "/vagrant/update.sh"
        ayo2.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh"
        ayo2.vm.provision "shell" , inline: "/vagrant/install_docker.sh"
        ayo2.vm.provision "shell" , inline: "/vagrant/install-gogs-compose.sh"
 	ayo2.vm.provision "shell" , inline: "/vagrant/install-gluster-compose.sh"
        ayo2.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"

          ayo2.vm.provider :libvirt do |domain|
            domain.memory = 1024
            domain.cpus = 1
          end
        end
	config.vm.define :ayo3 do |ayo3|
	ayo3.vm.hostname = "ayo3"
          ayo3.vm.network :public_network, ip: '192.168.7.205', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
 ayo3.vm.network :public_network, ip: '10.10.10.3', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
          ayo3.vm.synced_folder "./scripts", "/vagrant", disabled: false
         ayo3.vm.provision "shell" , inline: "/vagrant/update.sh"
        ayo3.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh"
        ayo3.vm.provision "shell" , inline: "/vagrant/install_docker.sh"
  	ayo3.vm.provision "shell" , inline: "/vagrant/install-gluster-compose.sh"
        ayo3.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"

          ayo3.vm.provider :libvirt do |domain|
            domain.memory = 1024
            domain.cpus = 1
          end
        end
end
