version: '2'
services: 
    node1: 
        image: gluster/gluster-centos
        ports: 
            - "addr:24007:24007"
            - "addr:24008:24008"
        privileged: true
        volumes: 
            - ./volumes/server1:/data
            - /potato/gluster/hosts:/etc/hosts
