# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure(2) do |config|
config.vm.provider :libvirt do |libvirt|
libvirt.host = '192.168.122.1'
libvirt.username = "4kvm"
libvirt.connect_via_ssh = true
libvirt.driver = "kvm"
libvirt.storage_pool_name = "VMS"
libvirt.storage :file, :size => '40G', :type => 'raw'
end

config.vm.box = "https://s3.otlabs.fr/index.php/s/tPeoTjFJ7I870GQ/download"
config.vm.provision "shell",
 run: "always",
 inline: " echo nameserver 8.8.8.8 > /etc/resolv.conf"
	config.vm.define :febi1 do |febi1|
	  febi1.vm.hostname = "febi1"	
  	  febi1.vm.network :public_network, ip: '192.168.7.211',netmask: "22", :dev => "enp4s0", :mode => 'bridge'
	  febi1.vm.network :public_network, ip: '10.10.35.1', netmask: "22", :dev => "enp4s0", :mode => 'bridge'  
	  febi1.vm.synced_folder "./scripts", "/vagrant", disabled: false
	  febi1.vm.provision "shell" , inline: "/vagrant/update.sh"
	  febi1.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh"
	  febi1.vm.provision "shell" , inline: "/vagrant/install-docker.sh"
	  febi1.vm.provision "shell" , inline: "/vagrant/deploy-gluster.sh"
	  febi1.vm.provision "shell" , inline: "/vagrant/deploy-gogs.sh"
	  febi1.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"

	  febi1.vm.provider :libvirt do |domain|
	  domain.storage :file, :size => '30G',:type => 'raw'
	    domain.memory = 1024
	    domain.cpus = 1
	  end
	end
	 config.vm.define :febi2 do |febi2| 
          febi2.vm.hostname = "febi2" 
		  febi2.vm.network :public_network, ip: '192.168.7.222', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
		  febi2.vm.network :public_network, ip: '192.168.2.191', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
 	      febi2.vm.network :public_network, ip: '10.10.35.2', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
          febi2.vm.synced_folder "./scripts", "/vagrant", disabled: false
          febi2.vm.provision "shell" , inline: "/vagrant/update.sh"
	      febi2.vm.provision "shell" , inline: "/vagrant/install-docker.sh"
          febi2.vm.provision "shell" , inline: "/vagrant/deploy-gluster.sh"
          febi2.vm.provision "shell" , inline: "/vagrant/deploy-gogs.sh"
	      febi2.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"
          febi2.vm.provider :libvirt do |domain|
		  domain.storage :file, :size => '30G',:type => 'raw'
            domain.memory = 1024
            domain.cpus = 1
          end
        end

	        config.vm.define :febi3 do |febi3|
          febi3.vm.hostname = "febi3"
          febi3.vm.network :public_network, ip: '192.168.7.224', netmask: "22", :dev => "enp4s0", :mode => 'bridge'
		  febi3.vm.network :public_network, ip: '192.168.2.197', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
	      febi3.vm.network :public_network, ip: '10.10.35.3', netmask: "22", :dev => "enp7s0.4", :mode => 'bridge'
          febi3.vm.synced_folder "./scripts", "/vagrant", disabled: false
          febi3.vm.provision "shell" , inline: "/vagrant/update.sh"
          febi3.vm.provision "shell" , inline: "/vagrant/provision-hdd.sh"
          febi3.vm.provision "shell" , inline: "/vagrant/install-docker.sh"
          febi3.vm.provision "shell" , inline: "/vagrant/deploy-gluster.sh"
          febi3.vm.provision "shell" , inline: "/vagrant/install-config-zabbixagent.sh"
          febi3.vm.provider :libvirt do |domain|
		  domain.storage :file, :size => '30G',:type => 'raw'
            domain.memory = 1024
            domain.cpus = 1
          end
        end



end
